/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client Config */
        get: operations["client_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Kinds */
        get: operations["list_kinds_api_kinds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detections */
        get: operations["detections_api_detections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validation Queue */
        get: operations["validation_queue_api_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detections/{detection_id}/verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verdict */
        post: operations["verdict_api_detections__detection_id__verdict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_api_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facilities */
        get: operations["facilities_api_facilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sensors */
        get: operations["sensors_api_sensors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets */
        get: operations["datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose */
        post: operations["propose_api_sources__source_id__propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attributions/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_attributions__link_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watches */
        get: operations["watches_api_watches_get"];
        put?: never;
        /** Create Watch */
        post: operations["create_watch_api_watches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Alert */
        patch: operations["patch_alert_api_alerts__alert_id__patch"];
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feedback */
        get: operations["feedback_api_feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/etl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Etls */
        get: operations["etls_api_etl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/etl/{name}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Job
         * @description Validate parameters against the step's schema before any job exists (gate H1).
         */
        post: operations["submit_job_api_etl__name__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explore Search */
        get: operations["explore_search_api_explore_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: number;
            /** State */
            state: string;
            /** Reason */
            reason: string | null;
            /** Created At */
            created_at: string;
            /** Watch */
            watch: {
                [key: string]: unknown;
            };
            /** Detection */
            detection: {
                [key: string]: unknown;
            };
        };
        /** AlertPatch */
        AlertPatch: {
            /**
             * State
             * @enum {string}
             */
            state: "seen" | "kept" | "dismissed";
            /**
             * Reason
             * @description e.g. "not a plume", "wrong source"
             */
            reason?: string | null;
        };
        /** AttributionLink */
        AttributionLink: {
            /** Id */
            id: number;
            /** Facility Id */
            facility_id: number;
            /** Facility */
            facility: string;
            /** Score */
            score: number | null;
            /** Method */
            method: string;
            /** Status */
            status: string;
            /** Valid From */
            valid_from: string | null;
            /** Valid To */
            valid_to: string | null;
            /** Decided By */
            decided_by: string | null;
        };
        /** CatalogSource */
        CatalogSource: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Url */
            url: string;
            /** Collections */
            collections: string[];
            /** Mirror */
            mirror: string;
            /** Licence */
            licence: string;
            /** Description */
            description: string;
        };
        /** ClientConfig */
        ClientConfig: {
            /** Name */
            name: string;
            /** Titiler Url */
            titiler_url: string;
            /** Auth Enabled */
            auth_enabled: boolean;
            /** Sources */
            sources: components["schemas"]["CatalogSource"][];
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Url */
            url: string | null;
            /** Licence */
            licence: string;
            /** Attribution */
            attribution: string | null;
            /** Sha256 */
            sha256: string;
            /** N Records */
            n_records: number | null;
            /** N Detections */
            n_detections: number;
            /** Fetched At */
            fetched_at: string | null;
        };
        /** DecisionIn */
        DecisionIn: {
            /** Confirm */
            confirm: boolean;
            /**
             * Valid From
             * @description When the link starts; open-ended
             */
            valid_from?: string | null;
        };
        /** EtlOut */
        EtlOut: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Description */
            description: string;
            /** Params Schema */
            params_schema: {
                [key: string]: unknown;
            };
            /** Writes */
            writes: string[];
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "closed";
            /**
             * T A
             * @description Last clear look before the event, if observed
             */
            t_a: string | null;
            /**
             * T B
             * @description First detection
             */
            t_b: string;
            /**
             * T C
             * @description Last detection
             */
            t_c: string;
            /**
             * T D
             * @description First clear look after the event, if observed
             */
            t_d: string | null;
            /** N Detections */
            n_detections: number;
            /** Q Mean Kg H */
            q_mean_kg_h: number | null;
            /** Q Sigma Kg H */
            q_sigma_kg_h: number | null;
            /** Source Id */
            source_id?: number | null;
            /** Kind */
            kind?: string | null;
        };
        /** Feature */
        Feature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Id */
            id?: number | string | null;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            } | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /** FeatureCollection */
        FeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["Feature"][];
        };
        /** FeedbackOut */
        FeedbackOut: {
            /** Id */
            id: number;
            /** Author */
            author: string;
            /** About */
            about: string;
            /** About Id */
            about_id: number;
            /** Kind */
            kind: string;
            /** Body */
            body: string | null;
            /** Action */
            action: string | null;
            /** Created At */
            created_at: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobIn */
        JobIn: {
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: number;
            /** Etl */
            etl: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "done" | "failed";
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Run Id */
            run_id?: number | null;
            /** Submitted By */
            submitted_by: string;
            /** Created At */
            created_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /** KindOut */
        KindOut: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Geometry */
            geometry: string;
            /** Validation */
            validation: string;
            /** Entities */
            entities: string[];
            /** Marks Schema */
            marks_schema: {
                [key: string]: unknown;
            };
        };
        /** Proposal */
        Proposal: {
            /** Id */
            id: number;
            /** Facility Id */
            facility_id: number;
            /** Score */
            score: number;
            /** Distance M */
            distance_m: number;
        };
        /** SensorOut */
        SensorOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Platform */
            platform: string | null;
            /** Agency */
            agency: string | null;
            /** Sensor Type */
            sensor_type: string | null;
            /** N Detections */
            n_detections: number;
        };
        /** SourceDetail */
        SourceDetail: {
            /** Id */
            id: number;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Source Type */
            source_type: string;
            /** Sector */
            sector: string | null;
            /** Country */
            country: string | null;
            /** Status */
            status: string;
            /** First Seen */
            first_seen: string | null;
            /** Last Seen */
            last_seen: string | null;
            /** Attrs */
            attrs: {
                [key: string]: unknown;
            };
            /** Xrefs */
            xrefs: components["schemas"]["Xref"][];
            /** Detections */
            detections: components["schemas"]["SourceDetection"][];
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Attributions */
            attributions: components["schemas"]["AttributionLink"][];
            who: components["schemas"]["Who"] | null;
        };
        /** SourceDetection */
        SourceDetection: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Observed At */
            observed_at: string;
            /** Q Kg H */
            q_kg_h: number | null;
            /** Q Sigma Kg H */
            q_sigma_kg_h: number | null;
            /** Sensor Id */
            sensor_id: number | null;
            /** Event Id */
            event_id: number | null;
        };
        /** Stats */
        Stats: {
            /** Predicted */
            predicted: number;
            /** Validated */
            validated: number;
            /** Rejected */
            rejected: number;
            /** Sources */
            sources: number;
            /** Alerts */
            alerts: number;
            /** Queued Jobs */
            queued_jobs: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerdictIn */
        VerdictIn: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "confirm" | "redraw" | "reject";
            /**
             * Geometry
             * @description Required for a redraw
             */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /** Note */
            note?: string | null;
        };
        /** VerdictOut */
        VerdictOut: {
            /** Label Id */
            label_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "predicted" | "validated" | "rejected";
            /** Alerts Raised */
            alerts_raised: number;
        };
        /** WatchIn */
        WatchIn: {
            /** Name */
            name: string;
            /**
             * Geometry
             * @description Polygon in EPSG:4326
             */
            geometry: {
                [key: string]: unknown;
            };
            /** Kind */
            kind?: string | null;
            /** Min Q Kg H */
            min_q_kg_h?: number | null;
        };
        /** WatchOut */
        WatchOut: {
            /** Id */
            id: number;
        };
        /** Who */
        Who: {
            /** At */
            at: string;
            /** Facility */
            facility: {
                [key: string]: unknown;
            };
            /** Asset */
            asset: {
                [key: string]: unknown;
            } | null;
            /** Operator */
            operator: {
                [key: string]: unknown;
            } | null;
            /** Owners */
            owners: {
                [key: string]: unknown;
            }[];
            /** Governments */
            governments: {
                [key: string]: unknown;
            }[];
        };
        /** Xref */
        Xref: {
            /** Provider */
            provider: string;
            /** Record Id */
            record_id: string;
            /** Match Score */
            match_score: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    client_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientConfig"];
                };
            };
        };
    };
    list_kinds_api_kinds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KindOut"][];
                };
            };
        };
    };
    detections_api_detections_get: {
        parameters: {
            query?: {
                status?: string | null;
                kind?: string | null;
                source_id?: number | null;
                bbox?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validation_queue_api_queue_get: {
        parameters: {
            query?: {
                kind?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verdict_api_detections__detection_id__verdict_post: {
        parameters: {
            query?: never;
            header?: {
                "x-geoapps-user"?: string | null;
            };
            path: {
                detection_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerdictIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerdictOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    source_api_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facilities_api_facilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    sensors_api_sensors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorOut"][];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
        };
    };
    propose_api_sources__source_id__propose_post: {
        parameters: {
            query?: {
                radius_m?: number;
            };
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_attributions__link_id__post: {
        parameters: {
            query?: never;
            header?: {
                "x-geoapps-user"?: string | null;
            };
            path: {
                link_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributionLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watches_api_watches_get: {
        parameters: {
            query?: {
                mine?: boolean;
            };
            header?: {
                "x-geoapps-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_watch_api_watches_post: {
        parameters: {
            query?: never;
            header?: {
                "x-geoapps-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_alerts_get: {
        parameters: {
            query?: {
                mine?: boolean;
            };
            header?: {
                "x-geoapps-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_alert_api_alerts__alert_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-geoapps-user"?: string | null;
            };
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_api_feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"][];
                };
            };
        };
    };
    etls_api_etl_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtlOut"][];
                };
            };
        };
    };
    submit_job_api_etl__name__jobs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-geoapps-user"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explore_search_api_explore_search_get: {
        parameters: {
            query: {
                source: string;
                bbox: string;
                collection?: string | null;
                start?: string | null;
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
