"""The only write path into the database (CLAUDE.md, ownership rule).

Each function takes an open ``Session`` and leaves committing to the caller
(``session_scope``), so one API request or one job step is one transaction (G4).
Geometries cross this boundary as GeoJSON dicts in EPSG:4326.

One module per schema; everything is re-exported here, so callers write
``repo.record_verdict(...)`` without caring where it lives.
"""

from geoapps_db.repo.attribution import (
    add_asset,
    add_org,
    decide_proposal,
    link_facility_asset,
    link_facility_government,
    link_source_facility,
    links_for_source,
    propose_source_facilities,
    set_asset_role,
    who_for_source,
)
from geoapps_db.repo.core import (
    add_assertion,
    add_xref,
    claim_job,
    counts,
    enqueue_job,
    finish_job,
    get_etl,
    get_job,
    list_datasets,
    list_etls,
    register_dataset,
    start_run,
    upsert_etl,
    xref_lookup,
    xref_map,
    xrefs_for,
)
from geoapps_db.repo.monitor import (
    EVENT_GAP_DAYS,
    add_location,
    add_observation,
    events_for_source,
    list_events,
    persistence,
    rechain_events,
    set_location_status,
)
from geoapps_db.repo.notify import (
    add_feedback,
    create_watch,
    list_alerts,
    list_feedback,
    set_alert_state,
    watches_geojson,
)
from geoapps_db.repo.ref import (
    add_facility,
    add_source,
    facilities_geojson,
    get_source,
    list_sensors,
    refresh_source_seen,
    source_detail,
    source_for_record,
    sources_geojson,
    upsert_sensor,
)
from geoapps_db.repo.review import (
    BETA,
    LAMBDA_HOURS,
    Q_REF_KG_H,
    TAU_HOURS,
    NotReviewable,
    VerdictResult,
    add_detection,
    detection_attr,
    detections_geojson,
    freeze_label_set,
    queue,
    queue_priority,
    record_verdict,
    refresh_imported_detection,
)

__all__ = [
    "BETA",
    "EVENT_GAP_DAYS",
    "LAMBDA_HOURS",
    "NotReviewable",
    "Q_REF_KG_H",
    "TAU_HOURS",
    "VerdictResult",
    "add_assertion",
    "add_asset",
    "add_detection",
    "add_facility",
    "add_feedback",
    "add_location",
    "add_observation",
    "add_org",
    "add_source",
    "add_xref",
    "claim_job",
    "counts",
    "create_watch",
    "decide_proposal",
    "detection_attr",
    "detections_geojson",
    "enqueue_job",
    "events_for_source",
    "facilities_geojson",
    "finish_job",
    "freeze_label_set",
    "get_etl",
    "get_job",
    "get_source",
    "link_facility_asset",
    "link_facility_government",
    "link_source_facility",
    "links_for_source",
    "list_alerts",
    "list_datasets",
    "list_etls",
    "list_events",
    "list_feedback",
    "list_sensors",
    "persistence",
    "propose_source_facilities",
    "queue",
    "queue_priority",
    "rechain_events",
    "record_verdict",
    "refresh_imported_detection",
    "refresh_source_seen",
    "register_dataset",
    "set_alert_state",
    "set_asset_role",
    "set_location_status",
    "source_detail",
    "source_for_record",
    "sources_geojson",
    "start_run",
    "upsert_etl",
    "upsert_sensor",
    "watches_geojson",
    "who_for_source",
    "xref_lookup",
    "xref_map",
    "xrefs_for",
]
