"""Initial schema: core, ref, review, notify.

The walking skeleton's tables (docs/design/01-design-plan.md, "Data placement").
Autogenerated from geoapps_db.models, then given the extensions and schemas
it needs. btree_gist is created now for the time-range exclusion constraints
that arrive with app 2's ownership links.

Revision ID: 0001
Revises:
Create Date: 2026-10-08
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


SCHEMAS = ("core", "ref", "review", "notify")


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    for schema in SCHEMAS:
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

    op.create_table(
        "etl",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("params_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "writes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_etl")),
        schema="core",
    )
    op.create_table(
        "run",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("stream", sa.String(length=128), server_default="nrt", nullable=False),
        sa.Column("etl", sa.String(length=128), nullable=True),
        sa.Column(
            "versions", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run")),
        schema="core",
    )
    op.create_geospatial_table(
        "watch",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=64), nullable=True),
        sa.Column("min_q_kg_h", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch")),
        schema="notify",
    )
    op.create_geospatial_index(
        "idx_watch_geom",
        "watch",
        ["geom"],
        unique=False,
        schema="notify",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_watch_owner"), "watch", ["owner"], unique=False, schema="notify")
    op.create_geospatial_table(
        "source",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=64), server_default="unknown", nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "attrs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
        schema="ref",
    )
    op.create_geospatial_index(
        "idx_source_geom",
        "source",
        ["geom"],
        unique=False,
        schema="ref",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_table(
        "job",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("etl", sa.String(length=128), nullable=False),
        sa.Column(
            "params", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("state", sa.String(length=16), server_default="queued", nullable=False),
        sa.Column("key", sa.String(length=256), nullable=True),
        sa.Column("submitted_by", sa.String(length=128), server_default="system", nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'done', 'failed')", name=op.f("ck_job_state")
        ),
        sa.ForeignKeyConstraint(["etl"], ["core.etl.name"], name=op.f("fk_job_etl_etl")),
        sa.ForeignKeyConstraint(["run_id"], ["core.run.id"], name=op.f("fk_job_run_id_run")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
        sa.UniqueConstraint("key", name=op.f("uq_job_key")),
        schema="core",
    )
    op.create_index(op.f("ix_job_etl"), "job", ["etl"], unique=False, schema="core")
    op.create_index(op.f("ix_job_state"), "job", ["state"], unique=False, schema="core")
    op.create_geospatial_table(
        "detection",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="predicted", nullable=False),
        sa.Column("scene_id", sa.String(length=256), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "marks", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("priority", sa.Float(), server_default="0", nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('predicted', 'validated', 'rejected')", name=op.f("ck_detection_status")
        ),
        sa.ForeignKeyConstraint(["run_id"], ["core.run.id"], name=op.f("fk_detection_run_id_run")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection")),
        schema="review",
    )
    op.create_geospatial_index(
        "idx_detection_geom",
        "detection",
        ["geom"],
        unique=False,
        schema="review",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_detection_kind"), "detection", ["kind"], unique=False, schema="review")
    op.create_index(
        op.f("ix_detection_priority"), "detection", ["priority"], unique=False, schema="review"
    )
    op.create_index(
        op.f("ix_detection_status"), "detection", ["status"], unique=False, schema="review"
    )
    op.create_table(
        "alert",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("watch_id", sa.BigInteger(), nullable=False),
        sa.Column("detection_id", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=16), server_default="raised", nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('raised', 'seen', 'kept', 'dismissed')", name=op.f("ck_alert_state")
        ),
        sa.ForeignKeyConstraint(
            ["detection_id"], ["review.detection.id"], name=op.f("fk_alert_detection_id_detection")
        ),
        sa.ForeignKeyConstraint(
            ["watch_id"],
            ["notify.watch.id"],
            name=op.f("fk_alert_watch_id_watch"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert")),
        sa.UniqueConstraint(
            "watch_id", "detection_id", name=op.f("uq_alert_watch_id_detection_id")
        ),
        schema="notify",
    )
    op.create_index(
        op.f("ix_alert_detection_id"), "alert", ["detection_id"], unique=False, schema="notify"
    )
    op.create_index(op.f("ix_alert_watch_id"), "alert", ["watch_id"], unique=False, schema="notify")
    op.create_geospatial_table(
        "label",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("detection_id", sa.BigInteger(), nullable=True),
        sa.Column("scene_id", sa.String(length=256), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("analyst", sa.String(length=128), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict IN ('confirm', 'redraw', 'reject')", name=op.f("ck_label_verdict")
        ),
        sa.ForeignKeyConstraint(
            ["detection_id"], ["review.detection.id"], name=op.f("fk_label_detection_id_detection")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_label")),
        schema="review",
    )
    op.create_index(
        op.f("ix_label_detection_id"), "label", ["detection_id"], unique=False, schema="review"
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("alert_id", sa.BigInteger(), nullable=False),
        sa.Column("channel", sa.String(length=32), server_default="in_app", nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["notify.alert.id"],
            name=op.f("fk_outbox_alert_id_alert"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
        schema="notify",
    )
    op.create_index(
        op.f("ix_outbox_alert_id"), "outbox", ["alert_id"], unique=False, schema="notify"
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_outbox_alert_id"), table_name="outbox", schema="notify")
    op.drop_table("outbox", schema="notify")
    op.drop_index(op.f("ix_label_detection_id"), table_name="label", schema="review")
    op.drop_geospatial_table("label", schema="review")
    op.drop_index(op.f("ix_alert_watch_id"), table_name="alert", schema="notify")
    op.drop_index(op.f("ix_alert_detection_id"), table_name="alert", schema="notify")
    op.drop_table("alert", schema="notify")
    op.drop_index(op.f("ix_detection_status"), table_name="detection", schema="review")
    op.drop_index(op.f("ix_detection_priority"), table_name="detection", schema="review")
    op.drop_index(op.f("ix_detection_kind"), table_name="detection", schema="review")
    op.drop_geospatial_index(
        "idx_detection_geom",
        table_name="detection",
        schema="review",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("detection", schema="review")
    op.drop_index(op.f("ix_job_state"), table_name="job", schema="core")
    op.drop_index(op.f("ix_job_etl"), table_name="job", schema="core")
    op.drop_table("job", schema="core")
    op.drop_geospatial_index(
        "idx_source_geom",
        table_name="source",
        schema="ref",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("source", schema="ref")
    op.drop_index(op.f("ix_watch_owner"), table_name="watch", schema="notify")
    op.drop_geospatial_index(
        "idx_watch_geom",
        table_name="watch",
        schema="notify",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("watch", schema="notify")
    op.drop_table("run", schema="core")
    op.drop_table("etl", schema="core")
    # core keeps the Alembic version table; extensions are left for other users of the database
    for schema in ("notify", "review", "ref"):
        op.execute(f"DROP SCHEMA IF EXISTS {schema}")
